GuiType = {BUTTON = 0, LISTBOX = 1, CHECKBOX = 2, SLIDER = 3, TEXTBOX = 4}

ButtonType = {
	SINGLE_PLAYER = 0,
	MAP_EDITOR = 1,
	OPTIONS = 2,
	EXIT = 3,
	OK = 4,
	DEFAULTS = 5,
	BACK = 6,
	CONTROLS_TAB = 7,
	MOUSE_TAB = 8,
	VIDEO_TAB = 9,
	AUDIO_TAB = 10,
	MULTIPLAYER_TAB = 11,
	NEW_MAP = 12,
	NEW_MAP_OK = 13,
	LOAD_MAP = 14,
	LOAD_MAP_OK = 15,
	EXPORT = 16,
	PLAY = 17
}

ListboxType = {
	CONTROLS = 0,
	RESOLUTION = 1,
	MAPS = 2,
	UNITS = 3,
	SKYBOX_TEXTURES = 4,
	LAND_TEXTURES = 5,
	CPU_DIFFICULTIES = 6,
	FACTIONS = 7
}
