GuiType = {BUTTON = 0, LISTBOX = 1, CHECKBOX = 2, SLIDER = 3, TEXTBOX = 4}

ButtonType = {
	SINGLE_PLAYER = 0,
	MAP_EDITOR = 1,
	OPTIONS = 2,
	EXIT = 3,
	OK = 4,
	DEFAULTS = 5,
	BACK = 6,
	CONTROLS_TAB = 7,
	MOUSE_TAB = 8,
	VIDEO_TAB = 9,
	AUDIO_TAB = 10,
	MULTIPLAYER_TAB = 11
}
