--TYPE = {ATTACK = 0, BUILD = 1, MOVE = 2, GARRISON = 3, EJECT = 4, PATROL = 5, LAUNCH = 6};
WeaponClass = {HITSCAN = 0, SHELL = 1, TORPEDO = 2, CRUISE_MISSILE = 3}
UnitClass = {
	WAR_MECH = 0,
	TANK = 1,
	ARTILLERY = 2,
	ENGINEER = 3,
	TRANSPORT = 4,
	CARGO_SHIP = 5,
	CRUISER = 6,
	CARRIER = 7,
	MISSILE_SUBMARINE = 8,
	STEALTH_SUBMARINE = 9,
	LAND_FACTORY = 10,
	NAVAL_FACTORY = 11,
	MARKET = 12,
	LAB = 13,
	POINT_DEFENSE = 14
}
UnitType = {UNDERWATER = 0, SEA_LEVEL = 1, HOVER = 2, LAND = 3, AIR = 4}
ArmorType = {CAST = 0, COMBINED = 1, MECHANIC = 2, SHELL = 3, STEEL = 4}

modelPrefix = "Models/GameObjects/"
vehiclePrefix = modelPrefix .. "Units/Vehicles/"
structurePrefix = modelPrefix .. "Units/Structures/"

units = {
	weapons = {
		{{hitscan = true, rateOfFire = 100, fireSfx = PATH .. 'Sounds/Units/WarMechs/fire.ogg', damage = 50, maxRange = 3}},
		{{hitscan = true, rateOfFire = 500, fireSfx = PATH .. 'Sounds/Units/Tanks/attack.ogg', damage = 200, maxRange = 20}},
		{{hitscan = true, rateOfFire = 2000, fireSfx = PATH .. 'Sounds/Units/Tanks/attack.ogg', damage = 5000, maxRange = 45}},
		{},
		{},
		{},
		{{hitscan = true, rateOfFire = 200, fireSfx = PATH .. 'Sounds/Units/Cruisers/fire.ogg', damage = 300, maxRange = 15}},
		{{hitscan = true, rateOfFire = 200, fireSfx = PATH .. 'Sounds/Units/Cruisers/fire.ogg', damage = 300, maxRange = 15}},
		{{hitscan = true, rateOfFire = 200, fireSfx = PATH .. 'Sounds/Units/Cruisers/fire.ogg', damage = 300, maxRange = 15}},
		{{hitscan = true, rateOfFire = 200, fireSfx = PATH .. 'Sounds/Units/Cruisers/fire.ogg', damage = 300, maxRange = 15}},
		{},
		{
			{hitscan = false, rateOfFire = 500, fireSfx = PATH .. 'Sounds/Units/Submarines/fire.ogg', damage = 200, maxRange = 20, projectile = {id = 1, pos = {x = 0, y = -.27, z = 4.6}, rot = {w = 1, x = 0, y = 0, z = 0}}}, 
			{hitscan = false, rateOfFire = 500, fireSfx = PATH .. 'Sounds/Units/Submarines/fire.ogg', minRange = 5, maxRange = 30, projectile = {id = 0, pos = {x = 0, y = 2.44, z = -3.5}, rot = {w = .707, x = -.707, y = 0, z = 0}}}
		},
		{{hitscan = false, rateOfFire = 500, fireSfx = PATH .. 'Sounds/Units/Submarines/fire.ogg', damage = 200, maxRange = 20, projectile = {id = 1, pos = {x = 0, y = -.27, z = 4.6}, rot = {w = 1, x = 0, y = 0, z = 0}}}},
		{},
		{},
		{},
		{},
		{{hitscan = true, rateOfFire = 500, fireSfx = PATH .. 'Sounds/Units/WarMechs/fire.ogg', damage = 50, maxRange = 10}},
	},
	unitClass = {
		UnitClass.WAR_MECH,
		UnitClass.TANK,
		UnitClass.ARTILLERY,
		UnitClass.ENGINEER,
		UnitClass.TRANSPORT,
		UnitClass.CARGO_SHIP,
		UnitClass.CRUISER,
		UnitClass.CRUISER,
		UnitClass.CRUISER,
		UnitClass.CRUISER,
		UnitClass.CARRIER,
		UnitClass.MISSILE_SUBMARINE,
		UnitClass.STEALTH_SUBMARINE,
		UnitClass.LAND_FACTORY,
		UnitClass.NAVAL_FACTORY,
		UnitClass.MARKET,
		UnitClass.LAB,
		UnitClass.POINT_DEFENSE
	},
	
	unitType = {
		UnitType.LAND,
		UnitType.LAND,
		UnitType.LAND,
		UnitType.LAND,
		UnitType.HOVER,
		UnitType.HOVER,
		UnitType.SEA_LEVEL,
		UnitType.SEA_LEVEL,
		UnitType.SEA_LEVEL,
		UnitType.SEA_LEVEL,
		UnitType.SEA_LEVEL,
		UnitType.UNDERWATER,
		UnitType.UNDERWATER,
		UnitType.LAND,
		UnitType.LAND,
		UnitType.LAND,
		UnitType.LAND,
		UnitType.LAND
	},

	armor = {
		{ArmorType.MECHANIC},
		{ArmorType.STEEL},
		{ArmorType.MECHANIC},
		{ArmorType.MECHANIC},
		{ArmorType.CAST},
		{ArmorType.MECHANIC},
		{ArmorType.CAST},
		{ArmorType.STEEL},
		{ArmorType.CAST},
		{ArmorType.CAST},
		{ArmorType.STEEL, ArmorType.COMBINED},
		{},
		{},
		{},
		{},
		{},
		{},
		{}
	},
	
	isVehicle = {
		true, true, true, true, true, true, true, true, true, true, true, true, true, false, false, false, false, false
	},
	
	health = {500, 500, 600, 200, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500},
	cost = {500, 600, 200, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500},
	garrisonCapacity = {
		{}, 
		{}, 
		{}, 
		{}, 
		{}, 
		{}, 
		{},
		{2, 2, 2},
		{}, 
		{}, 
		{}, 
		{}, 
		{}, 
		{}, 
		{}, 
		{}, 
		{}, 
		{}, 
		{}
	},
	
	unitCornerPoints = {
	    {
					{x = 1.45, y = -4.11, z = -1.21}, 
					{x = -1.45, y = -4.11, z = -1.21}, 
					{x = -1.45, y = -4.11, z = 1.21}, 
					{x = 1.45, y = -4.11, z = 1.21}, 
					{x = 1.45, y = 4.11, z = -1.21}, 
					{x = -1.45, y = 4.11, z = -1.21}, 
					{x = -1.45, y = 4.11, z = 1.21}, 
					{x = 1.45, y = 4.11, z = 1.21}
	    },
	    {
					{x = 1.45, y = -4.11, z = -1.21}, 
					{x = -1.45, y = -4.11, z = -1.21}, 
					{x = -1.45, y = -4.11, z = 1.21}, 
					{x = 1.45, y = -4.11, z = 1.21}, 
					{x = 1.45, y = 4.11, z = -1.21}, 
					{x = -1.45, y = 4.11, z = -1.21}, 
					{x = -1.45, y = 4.11, z = 1.21}, 
					{x = 1.45, y = 4.11, z = 1.21}
	    },
	    {
					{x = 1.45, y = -4.11, z = -1.21}, 
					{x = -1.45, y = -4.11, z = -1.21}, 
					{x = -1.45, y = -4.11, z = 1.21}, 
					{x = 1.45, y = -4.11, z = 1.21}, 
					{x = 1.45, y = 4.11, z = -1.21}, 
					{x = -1.45, y = 4.11, z = -1.21}, 
					{x = -1.45, y = 4.11, z = 1.21}, 
					{x = 1.45, y = 4.11, z = 1.21}
	    },
	    {
					{x = .5, y = -.5, z = -7.05}, 
					{x = -.5, y = -.5, z = -7.05}, 
					{x = -.5, y = -.5, z = 6.4}, 
					{x = .5, y = -.5, z = 6.4},
					{x = .5, y = 3, z = -7.05}, 
					{x = -.5, y = 3, z = -7.05}, 
					{x = -.5, y = 3, z = 6.4}, 
					{x = .5, y = 3, z = 6.4}
	    },
	    {
					{x = .5, y = -.5, z = -3.4}, 
					{x = -.5, y = -.5, z = -3.4}, 
					{x = -.5, y = -.5, z = 3.4},
					{x = .5, y = -.4, z = 3.4}, 
					{x = .5, y = 2.1, z = -3.4}, 
					{x = -.5, y = 2, z = -3.4},
					{x = -.5, y = 2, z = 3.4}, 
					{x = .5, y = 2, z = 3.4}
	    },
	    {
					{x = 1, y = -.25, z = -1}, 
					{x = -1, y = -.25, z = -1}, 
					{x = -1, y = -.25, z = 1}, 
					{x = 1, y = -.25, z = 1}, 
					{x = 1, y = .8, z = -1}, 
					{x = -1, y = .8, z = -1}, 
					{x = -1, y = .8, z = 1}, 
					{x = 1, y = .8, z = 1}
	    },
	    {
					{x = 1, y = -.25, z = -1}, 
					{x = -1, y = -.25, z = -1}, 
					{x = -1, y = -.25, z = 1}, 
					{x = 1, y = -.25, z = 1}, 
					{x = 1, y = .8, z = -1}, 
					{x = -1, y = .8, z = -1}, 
					{x = -1, y = .8, z = 1}, 
					{x = 1, y = .8, z = 1}
	    },
	    {
					{x = 1, y = -.25, z = -1}, 
					{x = -1, y = -.25, z = -1}, 
					{x = -1, y = -.25, z = 1}, 
					{x = 1, y = -.25, z = 1}, 
					{x = 1, y = .8, z = -1}, 
					{x = -1, y = .8, z = -1}, 
					{x = -1, y = .8, z = 1}, 
					{x = 1, y = .8, z = 1}
	    },
	    {
					{x = 1, y = -.25, z = -1}, 
					{x = -1, y = -.25, z = -1}, 
					{x = -1, y = -.25, z = 1}, 
					{x = 1, y = -.25, z = 1}, 
					{x = 1, y = .8, z = -1}, 
					{x = -1, y = .8, z = -1}, 
					{x = -1, y = .8, z = 1}, 
					{x = 1, y = .8, z = 1}
	    },
	    {
					{x = 1, y = -.25, z = -1}, 
					{x = -1, y = -.25, z = -1}, 
					{x = -1, y = -.25, z = 1}, 
					{x = 1, y = -.25, z = 1}, 
					{x = 1, y = .8, z = -1}, 
					{x = -1, y = .8, z = -1}, 
					{x = -1, y = .8, z = 1}, 
					{x = 1, y = .8, z = 1}
	    },
	    {
					{x = .7, y = -.3, z = -4}, 
					{x = -.7, y = -.3, z = -4}, 
					{x = -.7, y = -.3, z = 3.4}, 
					{x = .7, y = -.3, z = 3.4}, 
					{x = .7, y = 2.9, z = -4}, 
					{x = -.7, y = 2.9, z = -4}, 
					{x = -.7, y = 2.9, z = 3.4}, 
					{x = .7, y = 2.9, z = 3.4}
	    },
	    {
					{x = .5, y = -.5, z = -6.1}, 
					{x = -.5, y = -.5, z = -6.1}, 
					{x = -.5, y = -.5, z = 5.2}, 
					{x = .5, y = -.5, z = 5.2}, 
					{x = .5, y = 2.2, z = -6.1}, 
					{x = -.5, y = 2.2, z = -6.1}, 
					{x = -.5, y = 2.2, z = 5.2}, 
					{x = .5, y = 2.2, z = 5.2}
	    },
	    {
					{x = 2, y = -.5, z = -10}, 
					{x = -2, y = -.5, z = -10}, 
					{x = -2, y = -.5, z = 9}, 
					{x = 2, y = -.5, z = 9}, 
					{x = 2, y = 5.5, z = -10}, 
					{x = -2, y = 5.5, z = -10}, 
					{x = -2, y = 5.5, z = 9}, 
					{x = 2, y = 5.5, z = 9}
	    },
	    {
					{x = 2, y = -1, z = -10}, 
					{x = -2, y = -1, z = -10}, 
					{x = -2, y = -1, z = 9}, 
					{x = 2, y = -1, z = 9}, 
					{x = 2, y = 4.5, z = -10}, 
					{x = -2, y = 4.5, z = -10}, 
					{x = -2, y = 4.5, z = 9}, 
					{x = 2, y = 4.5, z = 9}
	    },
	    {
					{x = .25, y = -.5, z = -2}, 
					{x = -.25, y = -.5, z = -2}, 
					{x = -.25, y = -.5, z = 3}, 
					{x = .25, y = -.5, z = 3}, 
					{x = .25, y = .7, z = -2}, 
					{x = -.25, y = .7, z = -2}, 
					{x = -.25, y = .7, z = 3}, 
					{x = .25, y = .7, z = 3}
	    },
	    {
					{x = .6, y =-.1, z =-1.3},
					{x = -.6, y =-.1, z =-1.3},
					{x = -.6, y =-.1, z =.8},
					{x = .6, y =-.1, z =.8},
					{x = .6, y =.3, z =-1.3},
					{x = -.6, y =.3, z =-1.3},
					{x = -.6, y =.3, z =.8},
					{x = .6, y =.3, z =.8}
	    },
	    {
					{x = .5, y =-.1, z =-1.3},
					{x = -.5, y =-.1, z =-1.3},
					{x = -.5, y =-.1, z =.7},
					{x = .5, y =-.1, z =.7},
					{x = .5, y =.15, z =-1.3},
					{x = -.5, y =.15, z =-1.3},
					{x = -.5, y =.15, z =.7},
					{x = .5, y =.15, z =.7}
	    },
	    {
					{x = .5, y =-.1, z =-1.3},
					{x = -.5, y =-.1, z =-1.3},
					{x = -.5, y =-.1, z =.7},
					{x = .5, y =-.1, z =.7},
					{x = .5, y =.15, z =-1.3},
					{x = -.5, y =.15, z =-1.3},
					{x = -.5, y =.15, z =.7},
					{x = .5, y =.15, z =.7}
	    },
	    {
					{x = .5, y =-.1, z =-1.3},
					{x = -.5, y =-.1, z =-1.3},
					{x = -.5, y =-.1, z =.7},
					{x = .5, y =-.1, z =.7},
					{x = .5, y =.15, z =-1.3},
					{x = -.5, y =.15, z =-1.3},
					{x = -.5, y =.15, z =.7},
					{x = .5, y =.15, z =.7}
	    },
	    {
					{x = .5, y =-.1, z =-1.3},
					{x = -.5, y =-.1, z =-1.3},
					{x = -.5, y =-.1, z =.7},
					{x = .5, y =-.1, z =.7},
					{x = .5, y =.15, z =-1.3},
					{x = -.5, y =.15, z =-1.3},
					{x = -.5, y =.15, z =.7},
					{x = .5, y =.15, z =.7}
	    },
	    {
					{x = .5, y =-.1, z =-1.3},
					{x = -.5, y =-.1, z =-1.3},
					{x = -.5, y =-.1, z =.7},
					{x = .5, y =-.1, z =.7},
					{x = .5, y =.15, z =-1.3},
					{x = -.5, y =.15, z =-1.3},
					{x = -.5, y =.15, z =.7},
					{x = .5, y =.15, z =.7}
	    },
	    {
					{x = .5, y =-.1, z =-1.3},
					{x = -.5, y =-.1, z =-1.3},
					{x = -.5, y =-.1, z =.7},
					{x = .5, y =-.1, z =.7},
					{x = .5, y =.15, z =-1.3},
					{x = -.5, y =.15, z =-1.3},
					{x = -.5, y =.15, z =.7},
					{x = .5, y =.15, z =.7}
	    }
	},
	unitCuboidDimensions = {
	    {
					{x = 1, y = 1, z = 1}, 
					{x = 1, y = 1, z = 1}, 
					{x = 1, y = 1, z = 1}, 
					{x = 1, y = 1, z = 1}, 
					{x = 1, y = 1, z = 1}, 
					{x = 1, y = 1, z = 1}, 
					{x = 1, y = 1, z = 1}, 
					{x = 1, y = 1, z = 1}
	    },
	    {
					{x = 1, y = 1, z = 1}, 
					{x = 1, y = 1, z = 1}, 
					{x = 1, y = 1, z = 1}, 
					{x = 1, y = 1, z = 1}, 
					{x = 1, y = 1, z = 1}, 
					{x = 1, y = 1, z = 1}, 
					{x = 1, y = 1, z = 1}, 
					{x = 1, y = 1, z = 1}
	    },
	    {
					{x = 1, y = 1, z = 1}, 
					{x = 1, y = 1, z = 1}, 
					{x = 1, y = 1, z = 1}, 
					{x = 1, y = 1, z = 1}, 
					{x = 1, y = 1, z = 1}, 
					{x = 1, y = 1, z = 1}, 
					{x = 1, y = 1, z = 1}, 
					{x = 1, y = 1, z = 1}
	    },
	    {
					{x = 1, y = 1, z = 1}, 
					{x = 1, y = 1, z = 1}, 
					{x = 1, y = 1, z = 1}, 
					{x = 1, y = 1, z = 1}, 
					{x = 1, y = 1, z = 1}, 
					{x = 1, y = 1, z = 1}, 
					{x = 1, y = 1, z = 1}, 
					{x = 1, y = 1, z = 1}
	    },
	    {
					{x = 1, y = 1, z = 1}, 
					{x = 1, y = 1, z = 1}, 
					{x = 1, y = 1, z = 1}, 
					{x = 1, y = 1, z = 1}, 
					{x = 1, y = 1, z = 1}, 
					{x = 1, y = 1, z = 1}, 
					{x = 1, y = 1, z = 1}, 
					{x = 1, y = 1, z = 1}
	    },
	    {
					{x = 1, y = 1, z = 1}, 
					{x = 1, y = 1, z = 1}, 
					{x = 1, y = 1, z = 1}, 
					{x = 1, y = 1, z = 1}, 
					{x = 1, y = 1, z = 1}, 
					{x = 1, y = 1, z = 1}, 
					{x = 1, y = 1, z = 1}, 
					{x = 1, y = 1, z = 1}
	    },
	    {
					{x = 1, y = 1, z = 1}, 
					{x = 1, y = 1, z = 1}, 
					{x = 1, y = 1, z = 1}, 
					{x = 1, y = 1, z = 1}, 
					{x = 1, y = 1, z = 1}, 
					{x = 1, y = 1, z = 1}, 
					{x = 1, y = 1, z = 1}, 
					{x = 1, y = 1, z = 1}
	    },
	    {
					{x = 1, y = 1, z = 1}, 
					{x = 1, y = 1, z = 1}, 
					{x = 1, y = 1, z = 1}, 
					{x = 1, y = 1, z = 1}, 
					{x = 1, y = 1, z = 1}, 
					{x = 1, y = 1, z = 1}, 
					{x = 1, y = 1, z = 1}, 
					{x = 1, y = 1, z = 1}
	    },
	    {
					{x = 1, y = 1, z = 1}, 
					{x = 1, y = 1, z = 1}, 
					{x = 1, y = 1, z = 1}, 
					{x = 1, y = 1, z = 1}, 
					{x = 1, y = 1, z = 1}, 
					{x = 1, y = 1, z = 1}, 
					{x = 1, y = 1, z = 1}, 
					{x = 1, y = 1, z = 1}
	    },
	    {
					{x = 1, y = 1, z = 1}, 
					{x = 1, y = 1, z = 1}, 
					{x = 1, y = 1, z = 1}, 
					{x = 1, y = 1, z = 1}, 
					{x = 1, y = 1, z = 1}, 
					{x = 1, y = 1, z = 1}, 
					{x = 1, y = 1, z = 1}, 
					{x = 1, y = 1, z = 1}
	    },
	    {
					{x = 1, y = 1, z = 1}, 
					{x = 1, y = 1, z = 1}, 
					{x = 1, y = 1, z = 1}, 
					{x = 1, y = 1, z = 1}, 
					{x = 1, y = 1, z = 1}, 
					{x = 1, y = 1, z = 1}, 
					{x = 1, y = 1, z = 1}, 
					{x = 1, y = 1, z = 1}
	    },
	    {
					{x = 1, y = 1, z = 1}, 
					{x = 1, y = 1, z = 1}, 
					{x = 1, y = 1, z = 1}, 
					{x = 1, y = 1, z = 1}, 
					{x = 1, y = 1, z = 1}, 
					{x = 1, y = 1, z = 1}, 
					{x = 1, y = 1, z = 1}, 
					{x = 1, y = 1, z = 1}
	    },
	    {
					{x = 1, y = 1, z = 1}, 
					{x = 1, y = 1, z = 1}, 
					{x = 1, y = 1, z = 1}, 
					{x = 1, y = 1, z = 1}, 
					{x = 1, y = 1, z = 1}, 
					{x = 1, y = 1, z = 1}, 
					{x = 1, y = 1, z = 1}, 
					{x = 1, y = 1, z = 1}
	    },
	    {
					{x = 1, y = 1, z = 1}, 
					{x = 1, y = 1, z = 1}, 
					{x = 1, y = 1, z = 1}, 
					{x = 1, y = 1, z = 1}, 
					{x = 1, y = 1, z = 1}, 
					{x = 1, y = 1, z = 1}, 
					{x = 1, y = 1, z = 1}, 
					{x = 1, y = 1, z = 1}
	    },
	    {
					{x = .1, y = .1, z = .1}, 
					{x = .1, y = .1, z = .1}, 
					{x = .1, y = .1, z = .1}, 
					{x = .1, y = .1, z = .1}, 
					{x = .1, y = .1, z = .1}, 
					{x = .1, y = .1, z = .1}, 
					{x = .1, y = .1, z = .1}, 
					{x = .1, y = .1, z = .1}
	    },
	    {
					{x = .1, y = .1, z = .1}, 
					{x = .1, y = .1, z = .1}, 
					{x = .1, y = .1, z = .1}, 
					{x = .1, y = .1, z = .1}, 
					{x = .1, y = .1, z = .1}, 
					{x = .1, y = .1, z = .1}, 
					{x = .1, y = .1, z = .1}, 
					{x = .1, y = .1, z = .1}
	    },
	    {
					{x = .1, y = .1, z = .1}, 
					{x = .1, y = .1, z = .1}, 
					{x = .1, y = .1, z = .1}, 
					{x = .1, y = .1, z = .1}, 
					{x = .1, y = .1, z = .1}, 
					{x = .1, y = .1, z = .1},
					{x = .1, y = .1, z = .1}, 
					{x = .1, y = .1, z = .1}
	    },
	    {
					{x = .1, y = .1, z = .1}, 
					{x = .1, y = .1, z = .1}, 
					{x = .1, y = .1, z = .1}, 
					{x = .1, y = .1, z = .1}, 
					{x = .1, y = .1, z = .1}, 
					{x = .1, y = .1, z = .1},
					{x = .1, y = .1, z = .1}, 
					{x = .1, y = .1, z = .1}
	    },
	    {
					{x = .1, y = .1, z = .1}, 
					{x = .1, y = .1, z = .1}, 
					{x = .1, y = .1, z = .1}, 
					{x = .1, y = .1, z = .1}, 
					{x = .1, y = .1, z = .1}, 
					{x = .1, y = .1, z = .1},
					{x = .1, y = .1, z = .1}, 
					{x = .1, y = .1, z = .1}
	    },
	    {
					{x = .1, y = .1, z = .1}, 
					{x = .1, y = .1, z = .1}, 
					{x = .1, y = .1, z = .1}, 
					{x = .1, y = .1, z = .1}, 
					{x = .1, y = .1, z = .1}, 
					{x = .1, y = .1, z = .1},
					{x = .1, y = .1, z = .1}, 
					{x = .1, y = .1, z = .1}
	    },
	    {
					{x = .1, y = .1, z = .1}, 
					{x = .1, y = .1, z = .1}, 
					{x = .1, y = .1, z = .1}, 
					{x = .1, y = .1, z = .1}, 
					{x = .1, y = .1, z = .1}, 
					{x = .1, y = .1, z = .1},
					{x = .1, y = .1, z = .1}, 
					{x = .1, y = .1, z = .1}
	    },
	    {
					{x = .1, y = .1, z = .1}, 
					{x = .1, y = .1, z = .1}, 
					{x = .1, y = .1, z = .1}, 
					{x = .1, y = .1, z = .1}, 
					{x = .1, y = .1, z = .1}, 
					{x = .1, y = .1, z = .1},
					{x = .1, y = .1, z = .1}, 
					{x = .1, y = .1, z = .1}
	    }
	},
	hitboxOffset = {
		{x = 0, y = 0, z = 0},
		{x = 0, y = 0, z = 0},
		{x = 0, y = 0, z = 0},
		{x = 0, y = 0, z = 0},
		{x = 0, y = 0, z = 0},
		{x = 0, y = 0, z = 0},
		{x = 0, y = 0, z = 0},
		{x = 0, y = 0, z = 0},
		{x = 0, y = 0, z = 0},
		{x = 0, y = 0, z = 0},
		{x = 0, y = 0, z = 0},
		{x = 0, y = 0, z = 0},
		{x = 0, y = 0, z = 0},
		{x = 0, y = 0, z = 0},
		{x = 0, y = 0, z = 0},
		{x = 0, y = 0, z = 0},
		{x = 0, y = 0, z = 0},
	},
	
	unitAxisLength = {8, 8, 8, 8, 6, 6, 6, 6, 6, 6, 5, 5, 8, 8, 7, 2, 2, 2, 2, 2, 2, 2},
	lineOfSight = {5, 8, 4, 4, 3, 3, 3, 3, 3, 3, 3, 6, 6, 3, 3, 8, 1, 1, 1, 1, 1},
	name = {
		'War mech',
		'Tank',
		'Artillery',
		'Engineer',
		'Transport',
		'Cargo ship',
		'Tactical cruiser',
		'Defensive cruiser',
		'Cheap cruiser',
		'Transport cruiser',
		'Heavy carrier',
		'Missile submarine',
		'Stealth submarine',
		'Land factory',
		'Naval factory',
		'Market',
		'Lab',
		'Point defense',
	},
	meshPath = {
		'warMech.xml',
		'tank.xml',
		'artillery.xml',
		'engineer.xml',
		'transport.xml',
		'cargoship.xml',
		'tacticalCruiser.xml',
		'defensiveCruiser.xml',
		'cheapCruiser.xml',
		'transportCruiser.xml',
		'heavyCarrier.xml',
		'missileSubmarine.xml',
		'stealthSubmarine.xml',
		'landFactory.xml',
		'navalFactory.xml',
		'market.xml',
		'lab.xml',
		'pointDefense.xml',
	},
	basePath = {
		PATH .. vehiclePrefix .. 'WarMechs/',
		PATH .. vehiclePrefix .. 'Tanks/',
		PATH .. vehiclePrefix .. 'Artillery/',
		PATH .. vehiclePrefix .. 'Engineers/',
		PATH .. vehiclePrefix .. 'Transports/',
		PATH .. vehiclePrefix .. 'Cargoships/',
		PATH .. vehiclePrefix .. 'Cruisers/',
		PATH .. vehiclePrefix .. 'Cruisers/',
		PATH .. vehiclePrefix .. 'Cruisers/',
		PATH .. vehiclePrefix .. 'Cruisers/',
		PATH .. vehiclePrefix .. 'Carriers/',
		PATH .. vehiclePrefix .. 'Submarines/',
		PATH .. vehiclePrefix .. 'Submarines/',
		PATH .. structurePrefix .. 'LandFactory/',
		PATH .. structurePrefix .. 'NavalFactory/',
		PATH .. structurePrefix .. 'Market/',
		PATH .. structurePrefix .. 'Lab/',
		PATH .. structurePrefix .. 'PointDefenses/'
	},
	selectionSfx = {
		PATH .. 'Sounds/Units/WarMechs/selection.ogg',
		PATH .. 'Sounds/Units/Tanks/selection.ogg',
		PATH .. 'Sounds/Units/Tanks/selection.ogg',
		PATH .. 'Sounds/Units/Engineers/selection.ogg',
		PATH .. 'Sounds/Units/Transports/selection.ogg',
		PATH .. 'Sounds/Units/Cargoships/selection.ogg',
		PATH .. 'Sounds/Units/Cruisers/selection.ogg',
		PATH .. 'Sounds/Units/Cruisers/selection.ogg',
		PATH .. 'Sounds/Units/Cruisers/selection.ogg',
		PATH .. 'Sounds/Units/Cruisers/selection.ogg',
		PATH .. 'Sounds/Units/Carriers/selection.ogg',
		PATH .. 'Sounds/Units/Submarines/selection.ogg',
		PATH .. 'Sounds/Units/Submarines/selection.ogg',
		PATH .. 'Sounds/Units/Sample/selection.ogg',
		PATH .. 'Sounds/Units/Sample/selection.ogg',
		PATH .. 'Sounds/Units/Sample/selection.ogg',
		PATH .. 'Sounds/Units/Sample/selection.ogg',
		PATH .. 'Sounds/Units/Sample/selection.ogg',
	},
	deathSfx = {
		PATH .. 'Sounds/SFX/Explosions/explosion01.ogg',
		PATH .. 'Sounds/SFX/Explosions/explosion01.ogg',
		PATH .. 'Sounds/SFX/Explosions/explosion01.ogg',
		PATH .. 'Sounds/SFX/Explosions/explosion01.ogg',
		PATH .. 'Sounds/SFX/Explosions/explosion01.ogg',
		PATH .. 'Sounds/SFX/Explosions/explosion01.ogg',
		PATH .. 'Sounds/SFX/Explosions/explosion01.ogg',
		PATH .. 'Sounds/SFX/Explosions/explosion01.ogg',
		PATH .. 'Sounds/SFX/Explosions/explosion01.ogg',
		PATH .. 'Sounds/SFX/Explosions/explosion01.ogg',
		PATH .. 'Sounds/SFX/Explosions/explosion01.ogg',
		PATH .. 'Sounds/SFX/Explosions/explosion01.ogg',
		PATH .. 'Sounds/SFX/Explosions/explosion01.ogg',
		PATH .. 'Sounds/SFX/Explosions/explosion01.ogg',
		PATH .. 'Sounds/SFX/Explosions/explosion01.ogg',
		PATH .. 'Sounds/SFX/Explosions/explosion01.ogg',
		PATH .. 'Sounds/SFX/Explosions/explosion01.ogg',
		PATH .. 'Sounds/SFX/Explosions/explosion01.ogg',
	}
}
